name: specta_bot_telegram
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  alfred: ^0.1.7
  galaxeus: ^0.0.3
  galaxeus_lib: ^0.0.10
  hive: ^2.2.3
  path: ^1.8.2
  supabase_client: ^0.0.9
  telegram_client: ^0.3.55
